/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    categories: Category;
    ingredients: Ingredient;
    products: Product;
    variants: Variant;
    suppliers: Supplier;
    purchaseOrders: PurchaseOrder;
    stockLots: StockLot;
    stockMovements: StockMovement;
    carts: Cart;
    otpChallenges: OtpChallenge;
    customers: Customer;
    orders: Order;
    transactions: Transaction;
    returns: Return;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    purchaseOrders: PurchaseOrdersSelect<false> | PurchaseOrdersSelect<true>;
    stockLots: StockLotsSelect<false> | StockLotsSelect<true>;
    stockMovements: StockMovementsSelect<false> | StockMovementsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    otpChallenges: OtpChallengesSelect<false> | OtpChallengesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  countryOfOrigin?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  definition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: string | null;
  cautions?: string | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  brand?: (number | null) | Brand;
  categories?: (number | Category)[] | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  howToUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full INCI list, verbatim from packaging (EN).
   */
  inci?: string | null;
  keyIngredients?: (number | Ingredient)[] | null;
  productType?:
    | (
        | 'cleanser'
        | 'toner'
        | 'essence'
        | 'serum'
        | 'ampoule'
        | 'moisturizer'
        | 'sunscreen'
        | 'mask'
        | 'exfoliator'
        | 'eyeCream'
        | 'shampoo'
        | 'conditioner'
        | 'hairTreatment'
        | 'tool'
        | 'set'
      )
    | null;
  /**
   * Powers the routine builder. Null for haircare and tools.
   */
  routineStep?: number | null;
  skinTypes?: ('dry' | 'oily' | 'combination' | 'sensitive' | 'normal' | 'acneProne')[] | null;
  concerns?:
    | ('acne' | 'pigmentation' | 'dullness' | 'aging' | 'pores' | 'redness' | 'hairfall' | 'dandruff' | 'frizz')[]
    | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  fulfilmentMode?: ('readyStock' | 'preOrder' | 'both') | null;
  /**
   * Powers FAQPage JSON-LD (§14.2). Minimum 3 per PDP (§14.3).
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  /**
   * THE identity spine (non-negotiable #1). Byte-identical in Meta catalog id, Pixel content_ids, CAPI contents[].id, Google feed id. Never change once live.
   */
  sku: string;
  optionSize?: string | null;
  optionShade?: string | null;
  optionBundle?: string | null;
  barcode?: string | null;
  /**
   * Regular price, BDT.
   */
  mrp: number;
  salePrice?: number | null;
  saleStart?: string | null;
  saleEnd?: string | null;
  /**
   * Required — Pathao rejects orders without weight.
   */
  weightGrams: number;
  preOrderLeadDays?: number | null;
  /**
   * Variant-specific shot (e.g. shade swatch).
   */
  image?: (number | null) | Media;
  active?: boolean | null;
  /**
   * Denormalized. Maintained ONLY by the stock-movement hook (Phase 2, non-negotiable #4). Never write directly.
   */
  availableQty?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  country?: string | null;
  contact?: string | null;
  defaultCurrency?: ('KRW' | 'USD') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchaseOrders".
 */
export interface PurchaseOrder {
  id: number;
  poNumber: string;
  supplier?: (number | null) | Supplier;
  currency?: ('KRW' | 'USD') | null;
  /**
   * Foreign → BDT.
   */
  fxRate: number;
  /**
   * Intake per line: variant, qty, unit cost (foreign) + the lot printed on the package.
   */
  lines?:
    | {
        variant: number | Variant;
        qty: number;
        unitCostForeign: number;
        lotCode?: string | null;
        mfgDate?: string | null;
        expDate?: string | null;
        id?: string | null;
      }[]
    | null;
  freightBDT?: number | null;
  dutyBDT?: number | null;
  vatAtImportBDT?: number | null;
  clearingBDT?: number | null;
  otherChargesBDT?: number | null;
  allocationBasis?: ('byValue' | 'byWeight' | 'byQty') | null;
  status?: ('draft' | 'ordered' | 'inTransit' | 'customs' | 'received' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockLots".
 */
export interface StockLot {
  id: number;
  variant: number | Variant;
  /**
   * The code printed on the package.
   */
  lotCode: string;
  mfgDate?: string | null;
  expDate?: string | null;
  qtyReceived?: number | null;
  /**
   * Maintained ONLY by the stock-movement hook (#4).
   */
  qtyAvailable?: number | null;
  qtyReserved?: number | null;
  qtyDamaged?: number | null;
  purchaseOrder?: (number | null) | PurchaseOrder;
  /**
   * Set at receive. Drives COGS. Hidden from packer/support in Phase 9 RBAC.
   */
  landedCostPerUnit?: number | null;
  receivedAt?: string | null;
  /**
   * Invoice, BL, customs release, brand authorization — surfaced on /verify.
   */
  importDocs?:
    | {
        doc: number | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('open' | 'depleted' | 'quarantined' | 'expired') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockMovements".
 */
export interface StockMovement {
  id: number;
  lot?: (number | null) | StockLot;
  variant: number | Variant;
  /**
   * Signed. + adds to available, − removes.
   */
  qty: number;
  type: 'receipt' | 'reserve' | 'release' | 'ship' | 'returnRestock' | 'damage' | 'adjustment' | 'expiryWriteoff';
  /**
   * e.g. purchaseOrder, order, return
   */
  refType?: string | null;
  refId?: string | null;
  actor?: (number | null) | User;
  at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  token: string;
  items?:
    | {
        variant: number | Variant;
        qty: number;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  /**
   * First-touch attribution — carried to the order for CAPI (Phase 6).
   */
  attribution?: {
    fbp?: string | null;
    fbc?: string | null;
    fbclid?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    landingPath?: string | null;
  };
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges".
 */
export interface OtpChallenge {
  id: number;
  phone: string;
  codeHash: string;
  expiresAt: string;
  attempts?: number | null;
  lockedUntil?: string | null;
  ip?: string | null;
  consumed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  phone: string;
  name?: string | null;
  email?: string | null;
  addresses?:
    | {
        address?: string | null;
        zone?: ('dhakaCity' | 'dhakaSub' | 'outside') | null;
        landmark?: string | null;
        id?: string | null;
      }[]
    | null;
  orderCount?: number | null;
  deliveredCount?: number | null;
  cancelledCount?: number | null;
  lifetimeValue?: number | null;
  blacklisted?: boolean | null;
  blacklistReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  channel?: ('web' | 'facebook' | 'phone' | 'walkIn') | null;
  customer?: (number | null) | Customer;
  phone?: string | null;
  email?: string | null;
  /**
   * Price + cost snapshots are mandatory — last month’s invoice must not change (§4.3).
   */
  items?:
    | {
        variant?: (number | null) | Variant;
        titleSnapshot?: string | null;
        skuSnapshot?: string | null;
        unitPriceSnapshot?: number | null;
        qty?: number | null;
        lineTotal?: number | null;
        fulfilmentMode?: string | null;
        lotAllocations?:
          | {
              lot?: (number | null) | StockLot;
              qty?: number | null;
              landedCostSnapshot?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  orderType?: ('ready' | 'preorder' | 'mixed') | null;
  subtotal?: number | null;
  discountTotal?: number | null;
  deliveryCharge?: number | null;
  grandTotal?: number | null;
  advanceRequired?: number | null;
  advancePaid?: number | null;
  /**
   * What the courier collects (amount_to_collect) — never grandTotal (#2).
   */
  codAmount?: number | null;
  paymentMethod?: ('cod' | 'epsFull' | 'epsAdvance') | null;
  paymentStatus?: ('unpaid' | 'advancePaid' | 'paid' | 'refunded' | 'partialRefund') | null;
  fulfilmentStatus?:
    | ('pending' | 'confirmed' | 'packed' | 'handedToCourier' | 'inTransit' | 'delivered' | 'returned' | 'cancelled')
    | null;
  zone?: ('dhakaCity' | 'dhakaSub' | 'outside') | null;
  shipping?: {
    name?: string | null;
    phone?: string | null;
    altPhone?: string | null;
    address?: string | null;
    cityId?: string | null;
    zoneId?: string | null;
    areaId?: string | null;
    landmark?: string | null;
    postcode?: string | null;
  };
  courier?: {
    provider?: ('pathao' | 'steadfast' | 'manual') | null;
    consignmentId?: string | null;
    trackingCode?: string | null;
    pushedAt?: string | null;
    lastSyncAt?: string | null;
  };
  /**
   * fbp/fbc persisted here, not read from cookies at Purchase time (#8). eventIds for CAPI (Phase 6).
   */
  attribution?: {
    fbp?: string | null;
    fbc?: string | null;
    fbclid?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    clientIp?: string | null;
    userAgent?: string | null;
    landingPath?: string | null;
    eventIds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  riskFlags?: ('newCustomer' | 'highValue' | 'repeatCanceller' | 'addressMismatch' | 'inAppBrowser')[] | null;
  /**
   * Append-only.
   */
  timeline?:
    | {
        at?: string | null;
        actor?: string | null;
        event?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  order?: (number | null) | Order;
  merchantTransactionId: string;
  epsTransactionId?: string | null;
  amount?: number | null;
  purpose?: ('advance' | 'full') | null;
  status?: ('pending' | 'success' | 'failed' | 'cancelled' | 'unknown') | null;
  rawInit?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawVerify?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  verifiedAt?: string | null;
  financialEntity?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number;
  order?: (number | null) | Order;
  type?: ('rto' | 'customerReturn') | null;
  items?:
    | {
        variant?: (number | null) | Variant;
        qty?: number | null;
        condition?: ('resellable' | 'damaged') | null;
        id?: string | null;
      }[]
    | null;
  reason?: string | null;
  condition?: ('resellable' | 'damaged') | null;
  restockLot?: (number | null) | StockLot;
  refundAmount?: number | null;
  refundMethod?: string | null;
  status?: ('open' | 'processed' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'purchaseOrders';
        value: number | PurchaseOrder;
      } | null)
    | ({
        relationTo: 'stockLots';
        value: number | StockLot;
      } | null)
    | ({
        relationTo: 'stockMovements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'otpChallenges';
        value: number | OtpChallenge;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'returns';
        value: number | Return;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  countryOfOrigin?: T;
  story?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  definition?: T;
  benefits?: T;
  cautions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  categories?: T;
  shortDescription?: T;
  description?: T;
  howToUse?: T;
  inci?: T;
  keyIngredients?: T;
  productType?: T;
  routineStep?: T;
  skinTypes?: T;
  concerns?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  fulfilmentMode?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  optionSize?: T;
  optionShade?: T;
  optionBundle?: T;
  barcode?: T;
  mrp?: T;
  salePrice?: T;
  saleStart?: T;
  saleEnd?: T;
  weightGrams?: T;
  preOrderLeadDays?: T;
  image?: T;
  active?: T;
  availableQty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  contact?: T;
  defaultCurrency?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchaseOrders_select".
 */
export interface PurchaseOrdersSelect<T extends boolean = true> {
  poNumber?: T;
  supplier?: T;
  currency?: T;
  fxRate?: T;
  lines?:
    | T
    | {
        variant?: T;
        qty?: T;
        unitCostForeign?: T;
        lotCode?: T;
        mfgDate?: T;
        expDate?: T;
        id?: T;
      };
  freightBDT?: T;
  dutyBDT?: T;
  vatAtImportBDT?: T;
  clearingBDT?: T;
  otherChargesBDT?: T;
  allocationBasis?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockLots_select".
 */
export interface StockLotsSelect<T extends boolean = true> {
  variant?: T;
  lotCode?: T;
  mfgDate?: T;
  expDate?: T;
  qtyReceived?: T;
  qtyAvailable?: T;
  qtyReserved?: T;
  qtyDamaged?: T;
  purchaseOrder?: T;
  landedCostPerUnit?: T;
  receivedAt?: T;
  importDocs?:
    | T
    | {
        doc?: T;
        label?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockMovements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  lot?: T;
  variant?: T;
  qty?: T;
  type?: T;
  refType?: T;
  refId?: T;
  actor?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  token?: T;
  items?:
    | T
    | {
        variant?: T;
        qty?: T;
        id?: T;
      };
  phone?: T;
  attribution?:
    | T
    | {
        fbp?: T;
        fbc?: T;
        fbclid?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        landingPath?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges_select".
 */
export interface OtpChallengesSelect<T extends boolean = true> {
  phone?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  lockedUntil?: T;
  ip?: T;
  consumed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  phone?: T;
  name?: T;
  email?: T;
  addresses?:
    | T
    | {
        address?: T;
        zone?: T;
        landmark?: T;
        id?: T;
      };
  orderCount?: T;
  deliveredCount?: T;
  cancelledCount?: T;
  lifetimeValue?: T;
  blacklisted?: T;
  blacklistReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  channel?: T;
  customer?: T;
  phone?: T;
  email?: T;
  items?:
    | T
    | {
        variant?: T;
        titleSnapshot?: T;
        skuSnapshot?: T;
        unitPriceSnapshot?: T;
        qty?: T;
        lineTotal?: T;
        fulfilmentMode?: T;
        lotAllocations?:
          | T
          | {
              lot?: T;
              qty?: T;
              landedCostSnapshot?: T;
              id?: T;
            };
        id?: T;
      };
  orderType?: T;
  subtotal?: T;
  discountTotal?: T;
  deliveryCharge?: T;
  grandTotal?: T;
  advanceRequired?: T;
  advancePaid?: T;
  codAmount?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  fulfilmentStatus?: T;
  zone?: T;
  shipping?:
    | T
    | {
        name?: T;
        phone?: T;
        altPhone?: T;
        address?: T;
        cityId?: T;
        zoneId?: T;
        areaId?: T;
        landmark?: T;
        postcode?: T;
      };
  courier?:
    | T
    | {
        provider?: T;
        consignmentId?: T;
        trackingCode?: T;
        pushedAt?: T;
        lastSyncAt?: T;
      };
  attribution?:
    | T
    | {
        fbp?: T;
        fbc?: T;
        fbclid?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        clientIp?: T;
        userAgent?: T;
        landingPath?: T;
        eventIds?: T;
      };
  riskFlags?: T;
  timeline?:
    | T
    | {
        at?: T;
        actor?: T;
        event?: T;
        note?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  order?: T;
  merchantTransactionId?: T;
  epsTransactionId?: T;
  amount?: T;
  purpose?: T;
  status?: T;
  rawInit?: T;
  rawVerify?: T;
  verifiedAt?: T;
  financialEntity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  order?: T;
  type?: T;
  items?:
    | T
    | {
        variant?: T;
        qty?: T;
        condition?: T;
        id?: T;
      };
  reason?: T;
  condition?: T;
  restockLot?: T;
  refundAmount?: T;
  refundMethod?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}