/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    categories: Category;
    ingredients: Ingredient;
    products: Product;
    variants: Variant;
    suppliers: Supplier;
    purchaseOrders: PurchaseOrder;
    stockLots: StockLot;
    stockMovements: StockMovement;
    carts: Cart;
    otpChallenges: OtpChallenge;
    customers: Customer;
    orders: Order;
    transactions: Transaction;
    returns: Return;
    capiQueue: CapiQueue;
    accounts: Account;
    journalEntries: JournalEntry;
    journalLines: JournalLine;
    fiscalPeriods: FiscalPeriod;
    courierPayouts: CourierPayout;
    epsSettlements: EpsSettlement;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    purchaseOrders: PurchaseOrdersSelect<false> | PurchaseOrdersSelect<true>;
    stockLots: StockLotsSelect<false> | StockLotsSelect<true>;
    stockMovements: StockMovementsSelect<false> | StockMovementsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    otpChallenges: OtpChallengesSelect<false> | OtpChallengesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    capiQueue: CapiQueueSelect<false> | CapiQueueSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    journalEntries: JournalEntriesSelect<false> | JournalEntriesSelect<true>;
    journalLines: JournalLinesSelect<false> | JournalLinesSelect<true>;
    fiscalPeriods: FiscalPeriodsSelect<false> | FiscalPeriodsSelect<true>;
    courierPayouts: CourierPayoutsSelect<false> | CourierPayoutsSelect<true>;
    epsSettlements: EpsSettlementsSelect<false> | EpsSettlementsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * RBAC (§4.6). First user is owner; give real staff least-privilege roles. Only an owner can change roles. packer/support never see landed cost.
   */
  roles: ('owner' | 'manager' | 'inventory' | 'packer' | 'accounts' | 'support')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  countryOfOrigin?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show in the homepage category grid.
   */
  featuredOnHome?: boolean | null;
  /**
   * Lower shows first in the category grid.
   */
  homeOrder?: number | null;
  /**
   * Optional dedicated image for the homepage tile (falls back to `image`).
   */
  tileImage?: (number | null) | Media;
  /**
   * Tile accent colour.
   */
  accent?: ('celadon' | 'sky' | 'apricot' | 'rose-clay' | 'lilac') | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  definition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: string | null;
  cautions?: string | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Latin only. Auto-generated from the name/title if left blank.
   */
  slug?: string | null;
  brand?: (number | null) | Brand;
  categories?: (number | Category)[] | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  howToUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full INCI list, verbatim from packaging (EN).
   */
  inci?: string | null;
  keyIngredients?: (number | Ingredient)[] | null;
  productType?:
    | (
        | 'cleanser'
        | 'toner'
        | 'essence'
        | 'serum'
        | 'ampoule'
        | 'moisturizer'
        | 'sunscreen'
        | 'mask'
        | 'exfoliator'
        | 'eyeCream'
        | 'shampoo'
        | 'conditioner'
        | 'hairTreatment'
        | 'tool'
        | 'set'
      )
    | null;
  /**
   * Powers the routine builder. Null for haircare and tools.
   */
  routineStep?: number | null;
  skinTypes?: ('dry' | 'oily' | 'combination' | 'sensitive' | 'normal' | 'acneProne')[] | null;
  concerns?:
    | ('acne' | 'pigmentation' | 'dullness' | 'aging' | 'pores' | 'redness' | 'hairfall' | 'dandruff' | 'frizz')[]
    | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  fulfilmentMode?: ('readyStock' | 'preOrder' | 'both') | null;
  /**
   * Powers FAQPage JSON-LD (§14.2). Minimum 3 per PDP (§14.3).
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show in the best-sellers section.
   */
  isBestSeller?: boolean | null;
  /**
   * Adds a "New" badge.
   */
  isNew?: boolean | null;
  /**
   * Lower ranks first in featured/best-seller auto-fill. Leave blank to exclude from auto-fill.
   */
  featuredRank?: number | null;
  /**
   * Badge shown on product cards.
   */
  homeBadge?: ('none' | 'bestseller' | 'new' | 'sale' | 'limited') | null;
  /**
   * Short USP bullets shown on the PDP.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Curated "you may also like" products (falls back to auto-related when empty).
   */
  crossSell?: (number | Product)[] | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  /**
   * THE identity spine (non-negotiable #1). Byte-identical in Meta catalog id, Pixel content_ids, CAPI contents[].id, Google feed id. Never change once live.
   */
  sku: string;
  optionSize?: string | null;
  optionShade?: string | null;
  optionBundle?: string | null;
  barcode?: string | null;
  /**
   * Regular price, BDT.
   */
  mrp: number;
  salePrice?: number | null;
  saleStart?: string | null;
  saleEnd?: string | null;
  /**
   * Required — Pathao rejects orders without weight.
   */
  weightGrams: number;
  preOrderLeadDays?: number | null;
  /**
   * Variant-specific shot (e.g. shade swatch).
   */
  image?: (number | null) | Media;
  active?: boolean | null;
  /**
   * Denormalized. Maintained ONLY by the stock-movement hook (Phase 2, non-negotiable #4). Never write directly.
   */
  availableQty?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  country?: string | null;
  contact?: string | null;
  defaultCurrency?: ('KRW' | 'USD') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchaseOrders".
 */
export interface PurchaseOrder {
  id: number;
  poNumber: string;
  supplier?: (number | null) | Supplier;
  currency?: ('KRW' | 'USD') | null;
  /**
   * Foreign → BDT.
   */
  fxRate: number;
  /**
   * Intake per line: variant, qty, unit cost (foreign) + the lot printed on the package.
   */
  lines?:
    | {
        variant: number | Variant;
        qty: number;
        unitCostForeign: number;
        lotCode?: string | null;
        mfgDate?: string | null;
        expDate?: string | null;
        id?: string | null;
      }[]
    | null;
  freightBDT?: number | null;
  dutyBDT?: number | null;
  vatAtImportBDT?: number | null;
  clearingBDT?: number | null;
  otherChargesBDT?: number | null;
  allocationBasis?: ('byValue' | 'byWeight' | 'byQty') | null;
  status?: ('draft' | 'ordered' | 'inTransit' | 'customs' | 'received' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockLots".
 */
export interface StockLot {
  id: number;
  variant: number | Variant;
  /**
   * The code printed on the package.
   */
  lotCode: string;
  mfgDate?: string | null;
  expDate?: string | null;
  qtyReceived?: number | null;
  /**
   * Maintained ONLY by the stock-movement hook (#4).
   */
  qtyAvailable?: number | null;
  qtyReserved?: number | null;
  qtyDamaged?: number | null;
  purchaseOrder?: (number | null) | PurchaseOrder;
  /**
   * Set at receive. Drives COGS. Hidden from packer/support (RBAC §4.6).
   */
  landedCostPerUnit?: number | null;
  receivedAt?: string | null;
  /**
   * 3–6 months to EXP — set by the daily expiry cron (§10.3). Badge + clearance band. <3mo is FEFO-skipped by date.
   */
  shortExpiry?: boolean | null;
  /**
   * Invoice, BL, customs release, brand authorization — surfaced on /verify.
   */
  importDocs?:
    | {
        doc: number | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('open' | 'depleted' | 'quarantined' | 'expired') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockMovements".
 */
export interface StockMovement {
  id: number;
  lot?: (number | null) | StockLot;
  variant: number | Variant;
  /**
   * Signed. + adds to available, − removes.
   */
  qty: number;
  type: 'receipt' | 'reserve' | 'release' | 'ship' | 'returnRestock' | 'damage' | 'adjustment' | 'expiryWriteoff';
  /**
   * e.g. purchaseOrder, order, return
   */
  refType?: string | null;
  refId?: string | null;
  actor?: (number | null) | User;
  at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  token: string;
  items?:
    | {
        variant: number | Variant;
        qty: number;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  /**
   * First-touch attribution — carried to the order for CAPI (Phase 6).
   */
  attribution?: {
    fbp?: string | null;
    fbc?: string | null;
    fbclid?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    landingPath?: string | null;
  };
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges".
 */
export interface OtpChallenge {
  id: number;
  phone: string;
  codeHash: string;
  expiresAt: string;
  attempts?: number | null;
  lockedUntil?: string | null;
  ip?: string | null;
  consumed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  phone: string;
  name?: string | null;
  email?: string | null;
  addresses?:
    | {
        address?: string | null;
        zone?: ('dhakaCity' | 'dhakaSub' | 'outside') | null;
        landmark?: string | null;
        id?: string | null;
      }[]
    | null;
  orderCount?: number | null;
  deliveredCount?: number | null;
  cancelledCount?: number | null;
  lifetimeValue?: number | null;
  blacklisted?: boolean | null;
  blacklistReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  channel?: ('web' | 'facebook' | 'phone' | 'walkIn') | null;
  customer?: (number | null) | Customer;
  phone?: string | null;
  email?: string | null;
  /**
   * Price + cost snapshots are mandatory — last month’s invoice must not change (§4.3).
   */
  items?:
    | {
        variant?: (number | null) | Variant;
        titleSnapshot?: string | null;
        skuSnapshot?: string | null;
        unitPriceSnapshot?: number | null;
        qty?: number | null;
        lineTotal?: number | null;
        fulfilmentMode?: string | null;
        lotAllocations?:
          | {
              lot?: (number | null) | StockLot;
              qty?: number | null;
              landedCostSnapshot?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  orderType?: ('ready' | 'preorder' | 'mixed') | null;
  subtotal?: number | null;
  discountTotal?: number | null;
  deliveryCharge?: number | null;
  grandTotal?: number | null;
  advanceRequired?: number | null;
  advancePaid?: number | null;
  /**
   * What the courier collects (amount_to_collect) — never grandTotal (#2).
   */
  codAmount?: number | null;
  paymentMethod?: ('cod' | 'epsFull' | 'epsAdvance') | null;
  paymentStatus?: ('unpaid' | 'advancePaid' | 'paid' | 'refunded' | 'partialRefund') | null;
  fulfilmentStatus?:
    | ('pending' | 'confirmed' | 'packed' | 'handedToCourier' | 'inTransit' | 'delivered' | 'returned' | 'cancelled')
    | null;
  zone?: ('dhakaCity' | 'dhakaSub' | 'outside') | null;
  shipping?: {
    name?: string | null;
    phone?: string | null;
    altPhone?: string | null;
    address?: string | null;
    cityId?: string | null;
    zoneId?: string | null;
    areaId?: string | null;
    landmark?: string | null;
    postcode?: string | null;
  };
  courier?: {
    provider?: ('pathao' | 'steadfast' | 'manual') | null;
    consignmentId?: string | null;
    trackingCode?: string | null;
    pushedAt?: string | null;
    lastSyncAt?: string | null;
  };
  /**
   * fbp/fbc persisted here, not read from cookies at Purchase time (#8). eventIds for CAPI (Phase 6).
   */
  attribution?: {
    fbp?: string | null;
    fbc?: string | null;
    fbclid?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    clientIp?: string | null;
    userAgent?: string | null;
    landingPath?: string | null;
    eventIds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  riskFlags?: ('newCustomer' | 'highValue' | 'repeatCanceller' | 'addressMismatch' | 'inAppBrowser')[] | null;
  /**
   * Append-only.
   */
  timeline?:
    | {
        at?: string | null;
        actor?: string | null;
        event?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  order?: (number | null) | Order;
  merchantTransactionId: string;
  epsTransactionId?: string | null;
  amount?: number | null;
  purpose?: ('advance' | 'full') | null;
  status?: ('pending' | 'success' | 'failed' | 'cancelled' | 'unknown') | null;
  rawInit?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawVerify?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  verifiedAt?: string | null;
  financialEntity?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number;
  order?: (number | null) | Order;
  type?: ('rto' | 'customerReturn') | null;
  items?:
    | {
        variant?: (number | null) | Variant;
        qty?: number | null;
        condition?: ('resellable' | 'damaged') | null;
        id?: string | null;
      }[]
    | null;
  reason?: string | null;
  condition?: ('resellable' | 'damaged') | null;
  restockLot?: (number | null) | StockLot;
  refundAmount?: number | null;
  refundMethod?: string | null;
  status?: ('open' | 'processed' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capiQueue".
 */
export interface CapiQueue {
  id: number;
  eventName?: string | null;
  eventId?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'sent' | 'failed') | null;
  attempts?: number | null;
  nextAttemptAt?: string | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  /**
   * Permanent — never renumber (§12.1).
   */
  code: string;
  name: string;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  parent?: (number | null) | Account;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journalEntries".
 */
export interface JournalEntry {
  id: number;
  date: string;
  source: 'order' | 'purchaseOrder' | 'courierPayout' | 'epsSettlement' | 'manual' | 'systemClose';
  sourceId?: string | null;
  /**
   * Stable per (source,sourceId) — the idempotency + audit key, e.g. sale / cogs / po-receive.
   */
  ref?: string | null;
  memo?: string | null;
  status?: ('draft' | 'posted' | 'void') | null;
  postedBy?: (number | null) | User;
  postedAt?: string | null;
  period?: (number | null) | FiscalPeriod;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fiscalPeriods".
 */
export interface FiscalPeriod {
  id: number;
  /**
   * YYYY-MM.
   */
  month: string;
  status?: ('open' | 'closed') | null;
  closedAt?: string | null;
  closedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journalLines".
 */
export interface JournalLine {
  id: number;
  entry: number | JournalEntry;
  account: number | Account;
  debit?: number | null;
  credit?: number | null;
  orderRef?: string | null;
  poRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courierPayouts".
 */
export interface CourierPayout {
  id: number;
  provider?: ('pathao' | 'steadfast') | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  consignments?:
    | {
        consignmentId?: string | null;
        orderLink?: (number | null) | Order;
        codCollected?: number | null;
        courierFee?: number | null;
        rtoFee?: number | null;
        matched?: boolean | null;
        id?: string | null;
      }[]
    | null;
  codCollected?: number | null;
  courierFee?: number | null;
  rtoFee?: number | null;
  netReceived?: number | null;
  /**
   * Statement vs ledger. Never auto-post a non-zero variance (§12.5).
   */
  variance?: number | null;
  reconciledAt?: string | null;
  status?: ('pending' | 'reconciled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epsSettlements".
 */
export interface EpsSettlement {
  id: number;
  periodStart?: string | null;
  periodEnd?: string | null;
  transactions?:
    | {
        merchantTransactionId?: string | null;
        transaction?: (number | null) | Transaction;
        gross?: number | null;
        mdr?: number | null;
        matched?: boolean | null;
        id?: string | null;
      }[]
    | null;
  gross?: number | null;
  mdr?: number | null;
  netReceived?: number | null;
  /**
   * Statement vs ledger. Never auto-post a non-zero variance (§12.5).
   */
  variance?: number | null;
  reconciledAt?: string | null;
  status?: ('pending' | 'reconciled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Social-proof quotes for the storefront. Marketing only — not used for star-rating structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g. Banani, Dhaka
   */
  location?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Display only — never emitted as AggregateRating (#12).
   */
  rating?: number | null;
  quote: string;
  /**
   * Optional: the product this is about.
   */
  product?: (number | null) | Product;
  /**
   * Only approved testimonials appear on the storefront.
   */
  approved?: boolean | null;
  /**
   * Show in the homepage testimonials section.
   */
  featured?: boolean | null;
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'purchaseOrders';
        value: number | PurchaseOrder;
      } | null)
    | ({
        relationTo: 'stockLots';
        value: number | StockLot;
      } | null)
    | ({
        relationTo: 'stockMovements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'otpChallenges';
        value: number | OtpChallenge;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'returns';
        value: number | Return;
      } | null)
    | ({
        relationTo: 'capiQueue';
        value: number | CapiQueue;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'journalEntries';
        value: number | JournalEntry;
      } | null)
    | ({
        relationTo: 'journalLines';
        value: number | JournalLine;
      } | null)
    | ({
        relationTo: 'fiscalPeriods';
        value: number | FiscalPeriod;
      } | null)
    | ({
        relationTo: 'courierPayouts';
        value: number | CourierPayout;
      } | null)
    | ({
        relationTo: 'epsSettlements';
        value: number | EpsSettlement;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  countryOfOrigin?: T;
  story?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  featuredOnHome?: T;
  homeOrder?: T;
  tileImage?: T;
  accent?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  definition?: T;
  benefits?: T;
  cautions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  categories?: T;
  shortDescription?: T;
  description?: T;
  howToUse?: T;
  inci?: T;
  keyIngredients?: T;
  productType?: T;
  routineStep?: T;
  skinTypes?: T;
  concerns?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  fulfilmentMode?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  isBestSeller?: T;
  isNew?: T;
  featuredRank?: T;
  homeBadge?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  crossSell?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  optionSize?: T;
  optionShade?: T;
  optionBundle?: T;
  barcode?: T;
  mrp?: T;
  salePrice?: T;
  saleStart?: T;
  saleEnd?: T;
  weightGrams?: T;
  preOrderLeadDays?: T;
  image?: T;
  active?: T;
  availableQty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  contact?: T;
  defaultCurrency?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchaseOrders_select".
 */
export interface PurchaseOrdersSelect<T extends boolean = true> {
  poNumber?: T;
  supplier?: T;
  currency?: T;
  fxRate?: T;
  lines?:
    | T
    | {
        variant?: T;
        qty?: T;
        unitCostForeign?: T;
        lotCode?: T;
        mfgDate?: T;
        expDate?: T;
        id?: T;
      };
  freightBDT?: T;
  dutyBDT?: T;
  vatAtImportBDT?: T;
  clearingBDT?: T;
  otherChargesBDT?: T;
  allocationBasis?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockLots_select".
 */
export interface StockLotsSelect<T extends boolean = true> {
  variant?: T;
  lotCode?: T;
  mfgDate?: T;
  expDate?: T;
  qtyReceived?: T;
  qtyAvailable?: T;
  qtyReserved?: T;
  qtyDamaged?: T;
  purchaseOrder?: T;
  landedCostPerUnit?: T;
  receivedAt?: T;
  shortExpiry?: T;
  importDocs?:
    | T
    | {
        doc?: T;
        label?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stockMovements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  lot?: T;
  variant?: T;
  qty?: T;
  type?: T;
  refType?: T;
  refId?: T;
  actor?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  token?: T;
  items?:
    | T
    | {
        variant?: T;
        qty?: T;
        id?: T;
      };
  phone?: T;
  attribution?:
    | T
    | {
        fbp?: T;
        fbc?: T;
        fbclid?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        landingPath?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges_select".
 */
export interface OtpChallengesSelect<T extends boolean = true> {
  phone?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  lockedUntil?: T;
  ip?: T;
  consumed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  phone?: T;
  name?: T;
  email?: T;
  addresses?:
    | T
    | {
        address?: T;
        zone?: T;
        landmark?: T;
        id?: T;
      };
  orderCount?: T;
  deliveredCount?: T;
  cancelledCount?: T;
  lifetimeValue?: T;
  blacklisted?: T;
  blacklistReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  channel?: T;
  customer?: T;
  phone?: T;
  email?: T;
  items?:
    | T
    | {
        variant?: T;
        titleSnapshot?: T;
        skuSnapshot?: T;
        unitPriceSnapshot?: T;
        qty?: T;
        lineTotal?: T;
        fulfilmentMode?: T;
        lotAllocations?:
          | T
          | {
              lot?: T;
              qty?: T;
              landedCostSnapshot?: T;
              id?: T;
            };
        id?: T;
      };
  orderType?: T;
  subtotal?: T;
  discountTotal?: T;
  deliveryCharge?: T;
  grandTotal?: T;
  advanceRequired?: T;
  advancePaid?: T;
  codAmount?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  fulfilmentStatus?: T;
  zone?: T;
  shipping?:
    | T
    | {
        name?: T;
        phone?: T;
        altPhone?: T;
        address?: T;
        cityId?: T;
        zoneId?: T;
        areaId?: T;
        landmark?: T;
        postcode?: T;
      };
  courier?:
    | T
    | {
        provider?: T;
        consignmentId?: T;
        trackingCode?: T;
        pushedAt?: T;
        lastSyncAt?: T;
      };
  attribution?:
    | T
    | {
        fbp?: T;
        fbc?: T;
        fbclid?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        clientIp?: T;
        userAgent?: T;
        landingPath?: T;
        eventIds?: T;
      };
  riskFlags?: T;
  timeline?:
    | T
    | {
        at?: T;
        actor?: T;
        event?: T;
        note?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  order?: T;
  merchantTransactionId?: T;
  epsTransactionId?: T;
  amount?: T;
  purpose?: T;
  status?: T;
  rawInit?: T;
  rawVerify?: T;
  verifiedAt?: T;
  financialEntity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  order?: T;
  type?: T;
  items?:
    | T
    | {
        variant?: T;
        qty?: T;
        condition?: T;
        id?: T;
      };
  reason?: T;
  condition?: T;
  restockLot?: T;
  refundAmount?: T;
  refundMethod?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capiQueue_select".
 */
export interface CapiQueueSelect<T extends boolean = true> {
  eventName?: T;
  eventId?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  type?: T;
  parent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journalEntries_select".
 */
export interface JournalEntriesSelect<T extends boolean = true> {
  date?: T;
  source?: T;
  sourceId?: T;
  ref?: T;
  memo?: T;
  status?: T;
  postedBy?: T;
  postedAt?: T;
  period?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journalLines_select".
 */
export interface JournalLinesSelect<T extends boolean = true> {
  entry?: T;
  account?: T;
  debit?: T;
  credit?: T;
  orderRef?: T;
  poRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fiscalPeriods_select".
 */
export interface FiscalPeriodsSelect<T extends boolean = true> {
  month?: T;
  status?: T;
  closedAt?: T;
  closedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courierPayouts_select".
 */
export interface CourierPayoutsSelect<T extends boolean = true> {
  provider?: T;
  periodStart?: T;
  periodEnd?: T;
  consignments?:
    | T
    | {
        consignmentId?: T;
        orderLink?: T;
        codCollected?: T;
        courierFee?: T;
        rtoFee?: T;
        matched?: T;
        id?: T;
      };
  codCollected?: T;
  courierFee?: T;
  rtoFee?: T;
  netReceived?: T;
  variance?: T;
  reconciledAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epsSettlements_select".
 */
export interface EpsSettlementsSelect<T extends boolean = true> {
  periodStart?: T;
  periodEnd?: T;
  transactions?:
    | T
    | {
        merchantTransactionId?: T;
        transaction?: T;
        gross?: T;
        mdr?: T;
        matched?: T;
        id?: T;
      };
  gross?: T;
  mdr?: T;
  netReceived?: T;
  variance?: T;
  reconciledAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  avatar?: T;
  rating?: T;
  quote?: T;
  product?: T;
  approved?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * ⚠ VAT NOT CONFIGURED. Stays 0 until the rate + Mushak form are confirmed with the VAT consultant (§12.4). Do not guess.
   */
  vatRatePercent?: number | null;
  /**
   * Are catalog prices VAT-inclusive? Confirm with the consultant.
   */
  vatInclusive?: boolean | null;
  /**
   * Invoice form label (§12.4) — switchable without a code change.
   */
  mushakForm?: string | null;
  /**
   * Printed on the invoice (§12.4).
   */
  seller?: {
    name?: string | null;
    address?: string | null;
    /**
     * BIN — required on a Mushak invoice. Add before go-live.
     */
    bin?: string | null;
    phone?: string | null;
  };
  /**
   * Drives hasMerchantReturnPolicy in Product JSON-LD (§14.2). Structured data must match the REAL policy — a wrong policy risks a Google manual action. Confirm before go-live.
   */
  returns?: {
    /**
     * Uncheck if opened cosmetics are non-returnable → emits MerchantReturnNotPermitted.
     */
    returnsAccepted?: boolean | null;
    /**
     * Days to return a damaged/wrong item.
     */
    returnWindowDays?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header, footer, announcement bar, identity, and marketing copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcementBar?: {
    enabled?: boolean | null;
    /**
     * Rotates through these (e.g. free-shipping threshold, hotline, offer).
     */
    messages?:
      | {
          text: string;
          linkLabel?: string | null;
          linkHref?: string | null;
          id?: string | null;
        }[]
      | null;
    background?: ('celadon-deep' | 'ink' | 'grad') | null;
  };
  header?: {
    /**
     * Optional logo image (falls back to the wordmark).
     */
    logo?: (number | null) | Media;
    wordmark?: string | null;
    tagline?: string | null;
    primaryNav?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    searchPlaceholder?: string | null;
  };
  footer?: {
    /**
     * Short brand line under the wordmark.
     */
    blurb?: string | null;
    columns?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    socials?:
      | {
          platform?: ('facebook' | 'instagram' | 'whatsapp' | 'youtube' | 'tiktok') | null;
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Payment marks shown in the footer + checkout.
     */
    paymentMethods?: ('cod' | 'bkash' | 'nagad' | 'rocket' | 'upay' | 'visa' | 'mastercard')[] | null;
    /**
     * Leave blank to auto-generate "© YEAR <wordmark>".
     */
    copyright?: string | null;
  };
  /**
   * Single source of truth for name/phone/address (feeds header, footer, JSON-LD, llms.txt).
   */
  businessIdentity?: {
    siteName?: string | null;
    phone?: string | null;
    /**
     * Digits only, country code first (wa.me format).
     */
    whatsappNumber?: string | null;
    email?: string | null;
    streetAddress?: string | null;
    locality?: string | null;
    /**
     * One-paragraph description for llms.txt / meta fallback.
     */
    aboutBlurb?: string | null;
  };
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * DISPLAY COPY ONLY. Never the numeric charges (#3) — those come from checkout terms.
   */
  deliveryPromise?: {
    freeShipHeadline?: string | null;
    zoneBlurb?: string | null;
    etaCopy?: string | null;
  };
  productPage?: {
    stockPromise?: string | null;
    preorderPromise?: string | null;
    authenticityCopy?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Add, remove and reorder the landing-page sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The homepage renders these top-to-bottom.
   */
  layout?:
    | (
        | HeroBlock
        | TrustBadgesBlock
        | FeaturedProductsBlock
        | CategoryGridBlock
        | PromoBannerBlock
        | BestSellersBlock
        | TestimonialsBlock
        | AuthenticityBlock
        | RichTextBlock
        | NewsletterBlock
        | CtaBlock
      )[]
    | null;
  /**
   * Search/social metadata. Falls back to title + short description if blank.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Small label above the headline.
   */
  eyebrow?: string | null;
  headline: string;
  /**
   * Word(s) to render in the gradient accent.
   */
  headlineAccent?: string | null;
  subheadline?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  /**
   * Hero visual (product / lifestyle).
   */
  image?: (number | null) | Media;
  floatingBadges?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  align?: ('left' | 'center') | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesBlock".
 */
export interface TrustBadgesBlock {
  heading?: string | null;
  badges?:
    | {
        icon?:
          | (
              | 'shield-check'
              | 'badge-check'
              | 'truck'
              | 'rotate-ccw'
              | 'headphones'
              | 'sparkles'
              | 'leaf'
              | 'lock'
              | 'star'
              | 'heart'
              | 'package-check'
              | 'phone'
            )
          | null;
        label: string;
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustBadges';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock".
 */
export interface FeaturedProductsBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Curated + ordered. Leave empty to auto-fill from featured/best-seller flags.
   */
  products?: (number | Product)[] | null;
  viewAll?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Leave empty to auto-fill from categories flagged "featured on home".
   */
  categories?: (number | Category)[] | null;
  layout?: ('bento' | 'grid') | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock".
 */
export interface PromoBannerBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  layout?: ('left' | 'right' | 'full') | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  /**
   * Optional: show from this time.
   */
  startAt?: string | null;
  /**
   * Optional: hide after this time.
   */
  endAt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BestSellersBlock".
 */
export interface BestSellersBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Leave empty to auto-fill from the "best seller" flag.
   */
  products?: (number | Product)[] | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bestSellers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthenticityBlock".
 */
export interface AuthenticityBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  verifyCta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'authenticity';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  align?: ('left' | 'center') | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  heading?: string | null;
  subheading?: string | null;
  placeholder?: string | null;
  ctaLabel?: string | null;
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  subheading?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /search, /products/slug, https://wa.me/...
     */
    href?: string | null;
  };
  /**
   * Background treatment for this section.
   */
  theme?: ('paper' | 'cloud' | 'mist' | 'mesh-hero' | 'mesh-mint' | 'mesh-bloom' | 'ink') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  vatRatePercent?: T;
  vatInclusive?: T;
  mushakForm?: T;
  seller?:
    | T
    | {
        name?: T;
        address?: T;
        bin?: T;
        phone?: T;
      };
  returns?:
    | T
    | {
        returnsAccepted?: T;
        returnWindowDays?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        messages?:
          | T
          | {
              text?: T;
              linkLabel?: T;
              linkHref?: T;
              id?: T;
            };
        background?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        wordmark?: T;
        tagline?: T;
        primaryNav?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        searchPlaceholder?: T;
      };
  footer?:
    | T
    | {
        blurb?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        socials?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        paymentMethods?: T;
        copyright?: T;
      };
  businessIdentity?:
    | T
    | {
        siteName?: T;
        phone?: T;
        whatsappNumber?: T;
        email?: T;
        streetAddress?: T;
        locality?: T;
        aboutBlurb?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  deliveryPromise?:
    | T
    | {
        freeShipHeadline?: T;
        zoneBlurb?: T;
        etaCopy?: T;
      };
  productPage?:
    | T
    | {
        stockPromise?: T;
        preorderPromise?: T;
        authenticityCopy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        trustBadges?: T | TrustBadgesBlockSelect<T>;
        featuredProducts?: T | FeaturedProductsBlockSelect<T>;
        categoryGrid?: T | CategoryGridBlockSelect<T>;
        promoBanner?: T | PromoBannerBlockSelect<T>;
        bestSellers?: T | BestSellersBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        authenticity?: T | AuthenticityBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  headlineAccent?: T;
  subheadline?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  floatingBadges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  align?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesBlock_select".
 */
export interface TrustBadgesBlockSelect<T extends boolean = true> {
  heading?: T;
  badges?:
    | T
    | {
        icon?: T;
        label?: T;
        sub?: T;
        id?: T;
      };
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock_select".
 */
export interface FeaturedProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  products?: T;
  viewAll?:
    | T
    | {
        label?: T;
        href?: T;
      };
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock_select".
 */
export interface CategoryGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  categories?: T;
  layout?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock_select".
 */
export interface PromoBannerBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  layout?: T;
  theme?: T;
  startAt?: T;
  endAt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BestSellersBlock_select".
 */
export interface BestSellersBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  products?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthenticityBlock_select".
 */
export interface AuthenticityBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  points?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  verifyCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  align?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  placeholder?: T;
  ctaLabel?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}